import {
    inputToDefinition
} from './typescript';

import { Introspection, SchemaType } from './interface';

let inputDefinition: SchemaType;
const schema: Introspection = require('../test/github.json');
schema.data.__schema.types.forEach((type) => {
    switch (type.name) {
        case 'AddCommentInput':
            inputDefinition = type;
            break;
        default:
            return null;
    }
});

const inputExpected = `/**
 * Autogenerated input type of AddComment
 */
export interface AddCommentInput {

    /**
     * A unique identifier for the client performing the mutation.
     */
    clientMutationId?: Optional<String>;

    /**
     * The Node ID of the subject to modify.
     */
    subjectId: NonNull<ID>;

    /**
     * The contents of the comment.
     */
    body: NonNull<String>;
}`;

test('Generate ' + inputDefinition.kind + ' definition', () => {
    expect(inputToDefinition(inputDefinition))
        .toBe(inputExpected;
});
